### ISSUE TITLE
Font is hard to read especially during the day on the background

### ISSUE THREAD

**Issue by ezhes** [AndrewKe/DriveSafe#1]
I just tried the app out (WWDC 2016 page) and Avenir Next ultra thin is a poor choice for usability especially because it's meant to be quickly glanced upon. I know, and overuse, AVN ultra light because it's slick but I've realized now that visibility is a major issue.

Also, good luck with the scholarship!

**Comment by arnav-gudibande** [comment]
Salman,

Thanks for your feedback. Yes, AVN Ultra thin is the definite "go to" for
slick fonts.
As for readability, we will work on making our app more user friendly.

Regards,
Arnav Gudibande
